name: Build Books

on:
 push:
  paths:
   - "src/**"
   - "build.gradle"

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
      distribution: "temurin"
      java-version: "17"
      cache: "gradle"

   - name: Run Gradle build
     run: gradle all

   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
      name: books
      path: build/
