name: Build and Release Books

on:
 push:
  branches:
   - main
  tags:
   - "v*"

jobs:
 build:
  runs-on: ubuntu-latest
  permissions:
   contents: write

  steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
      distribution: "temurin"
      java-version: "17"
      cache: "gradle"

   - name: Run Gradle build
     run: gradle all

   - name: Create zip archive
     if: startsWith(github.ref, 'refs/tags/v')
     run: |
      cd build
      zip -r ../books-${{ github.ref_name }}.zip .
      cd ..

   - name: Upload artifacts
     uses: actions/upload-artifact@v4
     with:
      name: books-build-output
      path: build/

   - name: Create GitHub Release
     if: startsWith(github.ref, 'refs/tags/v')
     uses: softprops/action-gh-release@v2
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      name: Release ${{ github.ref_name }}
      body: |
       Automated release for ${{ github.ref_name }}.
       Contains processed book files.
      files: |
       books-${{ github.ref_name }}.zip
